apiVersion: v1
kind: Service
metadata:
  name: projectpulse-postgres
  labels:
    app.kubernetes.io/name: projectpulse-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: projectpulse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: projectpulse-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
