apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-config
  labels:
    {{- include "projectpulse.labels" . | nindent 4 }}
data:
  APP_NAME: {{ default "ProjectPulse" .Values.backend.env.APP_NAME | quote }}
  APP_ENV: {{ default "production" .Values.backend.env.APP_ENV | quote }}
  APP_DEBUG: {{ default "false" .Values.backend.env.APP_DEBUG | quote }}
  APP_URL: {{ default "http://projectpulse.local" .Values.backend.env.APP_URL | quote }}
  APP_PORT: {{ .Values.backend.port | quote }}
  DB_CONNECTION: {{ default "pgsql" .Values.backend.env.DB_CONNECTION | quote }}
  DB_HOST: {{ default "projectpulse-postgres" .Values.backend.env.DB_HOST | quote }}
  DB_PORT: {{ default "5432" .Values.backend.env.DB_PORT | quote }}
  DB_DATABASE: {{ default "projectpulse" .Values.backend.env.DB_DATABASE | quote }}
  FRONTEND_URL: {{ default "http://projectpulse.local" .Values.backend.env.FRONTEND_URL | quote }}
  MOBILE_URL: {{ default "http://localhost:8100" .Values.backend.env.MOBILE_URL | quote }}
