apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-secret
  labels:
    {{- include "projectpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "secrets.APP_KEY is required" .Values.secrets.APP_KEY | quote }}
  DB_USERNAME: {{ required "secrets.DB_USERNAME is required" .Values.secrets.DB_USERNAME | quote }}
  DB_PASSWORD: {{ required "secrets.DB_PASSWORD is required" .Values.secrets.DB_PASSWORD | quote }}
  LLM_API_KEY: {{ .Values.secrets.LLM_API_KEY | quote }}
