apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  labels:
    {{- include "projectpulse.web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "projectpulse.web.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
